[package]
name = "kinode_lib"
authors = ["KinodeDAO"]
version = "0.5.3"
edition = "2021"
description = "A general-purpose sovereign cloud computing platform"
homepage = "https://kinode.org"
repository = "https://github.com/kinode-dao/kinode"
license = "Apache-2.0"

[dependencies]
lib = { path = "lib" }

[workspace]
members = [
    "lib", "kinode",
    "kinode/packages/app_store/app_store", "kinode/packages/app_store/ft_worker",
    "kinode/packages/app_store/download", "kinode/packages/app_store/install", "kinode/packages/app_store/uninstall",
    "kinode/packages/chess/chess",
    "kinode/packages/homepage/homepage",
    "kinode/packages/kns_indexer/kns_indexer",
    "kinode/packages/terminal/terminal",
    "kinode/packages/terminal/alias", "kinode/packages/terminal/cat", "kinode/packages/terminal/echo", "kinode/packages/terminal/hi", "kinode/packages/terminal/m", "kinode/packages/terminal/top",
    "kinode/packages/tester/tester", "kinode/packages/tester/test_runner",
]
default-members = ["lib"]
resolver = "2"

[profile.release]
strip = "symbols"
lto = true
panic = "abort"
codegen-units = 1
