[package]
name = "kinode"
authors = ["KinodeDAO"]
version = "0.5.3"
edition = "2021"
description = "A general-purpose sovereign cloud computing platform"
homepage = "https://kinode.org"
repository = "https://github.com/kinode-dao/kinode"
license = "Apache-2.0"

[lib]

[[bin]]
name = "kinode"
required-features = ["build-binary"]

[features]
build-binary = [
    "aes-gcm", "anyhow", "async-trait", "base64", "bincode", "blake3", "bytes",
    "cap-std", "chacha20poly1305", "chrono", "clap", "crossterm", "dashmap",
    "digest", "elliptic-curve", "flate2", "futures", "generic-array", "getrandom",
    "hex", "hkdf", "hmac", "http", "jwt", "log", "nohash-hasher", "num-traits",
    "open", "public-ip", "rand", "reqwest", "rmp-serde", "rocksdb", "route-recognizer",
    "rusqlite", "serde_json", "serde_urlencoded", "sha2", "snow", "static_dir",
    "tokio", "tokio-stream", "tokio-tungstenite", "url", "uuid", "warp",
    "wasmtime", "wasmtime-wasi", "zip",
]
simulation-mode = []

[build-dependencies]
reqwest = { version = "0.11.22", features = ["blocking"] }
sha2 = "0.10"
walkdir = "2.4"
zip = "0.6"

[dependencies]
aes-gcm = { version = "0.10.2", optional = true }
anyhow = { version = "1.0.71", optional = true }
async-trait = { version = "0.1.71", optional = true }
base64 = { version = "0.13", optional = true }
bincode = { version = "1.3.3", optional = true }
blake3 = { version = "1.4.1", optional = true }
bytes = { version = "1.4.0", optional = true }
cap-std = { version = "2.0.0", optional = true }
chacha20poly1305 = { version = "0.10.1", optional = true }
chrono = { version = "0.4.31", optional = true }
clap = { version = "4.4", features = ["derive"], optional = true }
crossterm = { version = "0.26.1", features = ["event-stream", "bracketed-paste"], optional = true }
dashmap = { version = "5.5.3", optional = true }
digest = { version = "0.10", optional = true }
elliptic-curve = { version = "0.13.8", features = ["ecdh"], optional = true }
ethers = "2.0"
ethers-providers = "2.0.9"
flate2 = { version = "1.0", optional = true }
futures = { version = "0.3", optional = true }
generic-array = { version = "0.14", optional = true }
getrandom = { version = "0.2.10", optional = true }
hex = { version = "0.4.3", optional = true }
hkdf = { version = "0.12.3", optional = true }
hmac = { version = "0.12", optional = true }
http = { version = "0.2.9", optional = true }
jwt = { version = "0.16", optional = true }
lazy_static = "1.4.0"
log = { version = "0.4.20", optional = true }
nohash-hasher = { version = "0.2.0", optional = true }
num-traits = { version = "0.2", optional = true }
open = { version = "5.0.0", optional = true }
public-ip = { version = "0.2.2", optional = true }
rand = { version = "0.8.4", optional = true }
reqwest = { version = "0.11.18", optional = true }
ring = "0.16.20"
rmp-serde = { version = "1.1.2", optional = true }
rocksdb = { version = "0.21.0", features = ["multi-threaded-cf"], optional = true }
route-recognizer = { version = "0.3.1", optional = true }
rusqlite = { version = "0.30.0", features = ["bundled"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
serde_urlencoded = { version = "0.7", optional = true }
sha2 = { version = "0.10", optional = true }
snow = { version = "0.9.3", features = ["ring-resolver"], optional = true }
static_dir = { version = "0.2.0", optional = true }
thiserror = "1.0"
tokio = { version = "1.28", features = ["fs", "macros", "rt-multi-thread", "signal", "sync"], optional = true }
tokio-stream = { version = "0.1.14", optional = true }
tokio-tungstenite = { version = "0.20.1", optional = true }
url = { version = "2.4.1", optional = true }
uuid = { version = "1.1.2", features = ["serde", "v4"], optional = true }
warp = { version = "0.3.5", optional = true }
wasmtime = { version = "15.0.1", optional = true }
wasmtime-wasi = { version = "15.0.1", optional = true }
zip = { version = "0.6", optional = true }
